package de.mats.NimSpiel.panels;

import de.mats.NimSpiel.Window;
import de.mats.NimSpiel.game.Bot;

import javax.swing.*;
import java.awt.*;

public class Main {
    private final Window window;
    private final Second second;
    private JComboBox<String> combobox;
    private JPanel panel;
    private JButton weiterButton;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public Main(Window window, Second second) {
        this.window = window;
        this.second = second;
    }

    private void createUIComponents() {
        combobox = new JComboBox<>(new String[]{"Bot", "anderer Spieler"});
        weiterButton = new JButton();
        weiterButton.addActionListener(e -> {
            if (combobox.getSelectedItem().toString().equals("Bot")) {
                Bot bot = new Bot();
                JTextField player2TextField = second.getPlayer2TextField();
                player2TextField.setEditable(false);
                player2TextField.setText(bot.getName());
                window.setBot(new Bot());
            }
            window.setContentPane(second.$$$getRootComponent$$$());
            window.pack();
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setEnabled(true);
        label1.setText("Spielmodus");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(label1, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 300;
        gbc.insets = new Insets(7, 0, 0, 0);
        panel.add(combobox, gbc);
        weiterButton.setIcon(new ImageIcon(getClass().getResource("/arrow_right.png")));
        weiterButton.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(7, 0, 7, 0);
        panel.add(weiterButton, gbc);
        label1.setLabelFor(combobox);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
